name = "HyperCalibration"
uuid = "ee002675-c223-4b35-9440-54b3dbf2facf"
version = "0.0.1"
authors = ["Miguel Masó <miguel.maso@upc.edu>", "MultiSimOLab"]

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
HyperFEM = "ddbf423a-3df4-409e-9685-3dc416cae46c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
ExperimentsCSVExt = "CSV"
HyperCalibrationPlots = "Plots"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]

[compat]
Aqua = "0.8"
CSV = "0.10"
Gridap = "0.19, 0.20"
HyperFEM = "0.0.3"
Plots = "1"
Printf = "1"
Test = "1"
julia = "1.10"
