name = "HyperCalibration"
uuid = "ee002675-c223-4b35-9440-54b3dbf2facf"
version = "0.0.1"
authors = ["Miguel Masó <miguel.maso@upc.edu>", "MultiSimOLab"]

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
HyperFEM = "ddbf423a-3df4-409e-9685-3dc416cae46c"

[compat]
Gridap = "0.19.11"
HyperFEM = "0.0.3"
